### ISSUE TITLE
Root Password Not Working & CTF Scenario Errors when Attempting to Create One.

### ISSUE THREAD

**Issue by kanoble88** [cliffe/SecGen#101]
For some reason when I try to create some scenarios I am able to log in with the default root 'puppet' password, however most of the time it will tell me the password is wrong so I tried to use the password that is the encrypted one in the Vagrant file and it will let me log in using that.  Is there a way for me to fix that?

Another issue I am having is that when I try to create a ctf vm using the basic_narrative.xml it won't create.  A little time after starting I get the error:

Error: can't add no data. Feeding  into sender_domain
Check the scenario, not enough data is generated for this datastore (store_domain) to access this index (all)
Failed to resolve scenario.
During scenario generation 1 module conflict(s) occured...
Re-attempting to resolve scenario (#1)...

and at the end I get:

No element specified, e.g. access="0", for access_json="['name']": using (0)
/usr/lib/ruby/2.3.0/json/common.rb:156:in `initialize': no implicit conversion of nil into String (TypeError)
	from /usr/lib/ruby/2.3.0/json/common.rb:156:in `new'
	from /usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from /home/keith/Documents/SecGen/SecGen/lib/objects/system.rb:185:in `block (2 levels) in select_modules'
	from /home/keith/Documents/SecGen/SecGen/lib/objects/system.rb:136:in `each'
	from /home/keith/Documents/SecGen/SecGen/lib/objects/system.rb:136:in `block in select_modules'
	from /home/keith/Documents/SecGen/SecGen/lib/objects/system.rb:135:in `each'
	from /home/keith/Documents/SecGen/SecGen/lib/objects/system.rb:135:in `select_modules'
	from /home/keith/Documents/SecGen/SecGen/lib/objects/system.rb:36:in `block in resolve_module_selection'
	from /home/keith/Documents/SecGen/SecGen/lib/objects/system.rb:35:in `each'
	from /home/keith/Documents/SecGen/SecGen/lib/objects/system.rb:35:in `resolve_module_selection'
	from secgen.rb:90:in `block in build_config'
	from secgen.rb:89:in `map!'
	from secgen.rb:89:in `build_config'
	from secgen.rb:172:in `run'
	from secgen.rb:297:in `<main>'

and it won't create the scenario, it just stops after that.  But I am able to create the flawed fortress and the nw cyber games.

**Comment by thomashaw** [comment]
Hi,

If you comment out the following block of code in the scenario.xml file you're running, SecGen will not  change the default password on the VM.

**    <build type="cleanup">
      <input into="root_password">
        <generator type="strong_password_generator"/>
      </input>
    </build>
**

I've just reverted a commit I made recently making some changes to the layout of the basic_narrative.xml scenario, if you update your branch it should generate now.

Thanks for the info and have fun!

**Comment by kanoble88** [comment]
Awesome thanks!  This program is fantastic for those of us new to CTF events and putting them together.

**Comment by kanoble88** [comment]
Is it supposed to create 3 VMs at a time?  When I look at my virtualbox after it says the VMs were created I have one for the decode me, one for into the wild and another for that escalated quickly.

**Comment by thomashaw** [comment]
Yes the flawed_fortress.xml scenario will generate 3 VMs. You can see how many VMs each scenario will create by looking at the number of `<system>` tags in the scenario xml file. 

The reason we have multiple VMs is because one box has a privilege escalation to root vulnerability. If that vulnerability is exploited successfully a bunch of the flags would be accessible without solving the other challenges.

**Comment by kanoble88** [comment]
Ohh I get it now.  Is is possible to export the flags for a VM to a CTF program like the Facebook CTF? I have been using that lately and was debating on copying the information from the XML to the facebook CTF using their json template.

**Comment by cliffe** [comment]
Hi @kanoble88 
It would be great if when outputting the project, SecGen also output the files in Facebook CTF format (and other front ends, such as CTFd).
Currently we have been focussing on our own CTF frontend.

We currently have multiple hints per flag, and even shared hints among flags where the flag requires multiple shared steps. We support this in our front end, where submitting a flag will unlock any shared hints (for example, two flags encoded different ways behind the same software vulnerability, share hints regarding the vulnerability). Also because of the nature of having a VM, means that you might find a flag, without knowing what challenge the flag was from. 

Not sure how compatible all that is with Facebook CTF, but the hints could be removed or simplified, and hopefully there is a way of making a single flag submission. Feel free to investigate and report back :)

Cheers.
