### ISSUE TITLE
Vagrant SSH keys: Connection Reset

### ISSUE THREAD

**Issue by Ysagi** [cliffe/SecGen#106]
Hello again.

I have installed the CTF-challenge, and everything looks okay. But after closing down vagrant "vagrant halt" and then starting the CTF again with "vagrant up" I get an connection reset for the SSH keys:

    decode_me: username: vagrant
    decode_me: SSH auth method: private key
    decode_me: Warning: Connection reset. Retrying...
    decode_me: Warning: Remote connection disconnect. Retrying...

    in_the_wild: SSH username: vagrant
    in_the_wild: SSH auth method: private key
    in_the_wild: Warning: Connection reset. Retrying...
    in_the_wild: Warning: Remote connection disconnect. Retrying...

    that_escalated_quickly: SSH username: vagrant
    that_escalated_quickly: SSH auth method: private key
    that_escalated_quickly: Warning: Connection reset. Retrying...
    that_escalated_quickly: Warning: Remote connection disconnect. Retrying...

Everything spins up and syncs, but why are the connection reset?

Thanks in advance.

Best regards Mattias

**Comment by thomashaw** [comment]
Hi @Ysagi,

The 'Warning: Connection reset. Retrying' warning occurs when vagrant is unsuccessful in connecting over ssh to a VM that it's man. This usually happens when the VM is still booting up, before the ssh service has started, but can be due to problems with the networking or SSH configurations of the basebox.

Does vagrant connect successfully eventually? If so I don't think it's anything to worry about.

Here's an example of my output when running 'vagrant halt' then 'vagrant up'.
``
Bringing machine 'decode_me' up with 'virtualbox' provider
==> decode_me: Clearing any previously set forwarded ports...
==> decode_me: Clearing any previously set network interfaces...
==> decode_me: Preparing network interfaces based on configuration...
    decode_me: Adapter 1: nat
    decode_me: Adapter 2: hostonly
==> decode_me: Forwarding ports...
    decode_me: 22 (guest) => 2222 (host) (adapter 1)
==> decode_me: Running 'pre-boot' VM customizations...
==> decode_me: Booting VM...
==> decode_me: Waiting for machine to boot. This may take a few minutes...
    decode_me: SSH address: 127.0.0.1:2222
    decode_me: SSH username: vagrant
    decode_me: SSH auth method: private key
    **decode_me: Warning: Remote connection disconnect. Retrying...**
**==> decode_me: Machine booted and ready!**
**==> decode_me: Checking for guest additions in VM...**
``

Cheers,
Tom
