### ISSUE TITLE
Intnetwork

### ISSUE THREAD

**Issue by WebForMotherfuckers** [cliffe/SecGen#165]
HI! I want to connect virtual machines to an existing internal network. How do I do this?

**Comment by jeremytourville** [comment]
Which hypervisor did you build the vms in?

**Comment by WebForMotherfuckers** [comment]
Vbox 6.0

**Comment by jeremytourville** [comment]
You need to change one of the network adapters to bridged.  SecGen/Vagrant sets  up two NICs - one NAT and one host only.  I'd change the NAT to bridged, reboot and see what you get.  You may need to tweak the network config settings in the OS as well but let's take one step at a time.  Let me know what happens when you've made that change.

**Comment by WebForMotherfuckers** [comment]
Thanks, everything worked out!!!
Can you tell me why I can't pass post-provision tests?
Here's a photo

![изображение](https://user-images.githubusercontent.com/60269694/81100476-4ac91a00-8f15-11ea-9e76-69613487d6be.png)

**Comment by firewallzer0** [comment]
I was wondering if there is a way to specify that VM's used the bridge connection rather than NAT in the creation process, I have already manually moved all my VM's to Bridged but is there a setting that I can configure so they are always using Bridged instead of NAT?

@WebForMotherfuckers It looks like there were only 3 tests that didn't run and the reason is right there in the image "Cannot test against dynamic IPs" Looks like everything else passed successfully as everything is green and the VMs were created.
