### ISSUE TITLE
unrecognized option `--esxi-disktype'

### ISSUE THREAD

**Issue by zero77** [cliffe/SecGen#187]
I am constantly getting the following error i have tried a range of different disk types like zeroedthick, thin and others but, they all return the same error.

error:
https://pastebin.com/raw/WCJBP0NC

**Comment by thompslu** [comment]
Hi zero77

Apart from this error you are receiving have you set the correct URL to point to your ESXi server. If it’s a lab that doesn’t use a DNS name then ensure you put the IP address of the server and edit the etc/hosts (not really the recommended way but it will do the job). If you do have DNS ensure it’s correctly setup along with vagrant for the provisioning. you may need to tweak vagrant slightly so it supports ESXi using the approach by dezull :- https://github.com/dezull/vagrant-vmware-esxi if you find a contact for dezull he may be able to give you better advice as in terms of the ESXi hypervisor.

Ensure you’ve also set up all the required VM network and adapters.

Regards

Thompslu

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zero77** [comment]
Thanks for your response, i am not using a host or domain name i am connecting based on the ip, though i dont know if the api url is correct.

> https://ip/rest/com/vmware/vapi/metadata/cli/command

**Comment by thompslu** [comment]
You will need to change IP after https:// to your local network for example  https://192.168.0.120/rest/com/vmware/vapi/metadata/cli/command



I’m not sure if the ESXi api comes with the server on default installation you would also need to research this, it’s been a while since I had ESXi running in my lab.

Just make sure that your development machine can see the network or maybe log in through the web portal to ensure ESXi server is running. You shouldn’t go wrong if you tweak all of the advice mentioned. Let me know how you get on.

Regards

Thompslu





Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zero77** [comment]
thanks, i will do some more investigation.

**Comment by zero77** [comment]
It looks like the api is read only in the free version, is it possible to use ssh instead of the api.

**Comment by zero77** [comment]
@ thompslu 
After doing some investigations, i believe that some API are unavailable if the free version of ESXI, for this to work you have to pay for the full version.
