### ISSUE TITLE
Issue With Running the Scenario

### ISSUE THREAD

**Issue by hrz0001** [cliffe/SecGen#192]
Hi, 

While running the Scenario, It Fails to resolve Scenario. Have tried reinstalling the scenario but its of no use. can anyone please suggest me.
![Failure](https://user-images.githubusercontent.com/80485899/118427980-8c90c100-b722-11eb-8b14-b8f7095a0ad4.PNG)

**Comment by thompslu** [comment]
What command are you trying to run to get the scenario working ? Please can you post it so I can advise.

Kind Regards

Luke Thompson
________________________________
From: hrz0001 ***@***.***>
Sent: Monday, May 17, 2021 4:14:47 AM
To: cliffe/SecGen ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cliffe/SecGen] Issue With Running the Scenario (#192)


Caution External Mail: Do not click any links or open any attachments unless you trust the sender and know that the content is safe.

Hi,

While running the Scenario, It Fails to resolve Scenario. Have tried reinstalling the scenario but its of no use. can anyone please suggest me.
[Failure]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F80485899%2F118427980-8c90c100-b722-11eb-8b14-b8f7095a0ad4.PNG&data=04%7C01%7Cl.thompson4763%40student.leedsbeckett.ac.uk%7C89648bce2fb84955d06f08d918e1ee21%7Cd79a81124fbe417aa112cd0fb490d85c%7C0%7C0%7C637568180918068374%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ik3sVMTCbxLnIxAIsEtq7N%2B1UcaHpUD5JM%2F8CZNrrjo%3D&reserved=0>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcliffe%2FSecGen%2Fissues%2F192&data=04%7C01%7Cl.thompson4763%40student.leedsbeckett.ac.uk%7C89648bce2fb84955d06f08d918e1ee21%7Cd79a81124fbe417aa112cd0fb490d85c%7C0%7C0%7C637568180918068374%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TB2m3Z%2FumVPBI%2Ba0HFrYAlKp8r3zUb%2BwT27vVOwhdy0%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPFYKO2WJBBDJ5WCRQSVF2LTOCC2PANCNFSM447SFNPA&data=04%7C01%7Cl.thompson4763%40student.leedsbeckett.ac.uk%7C89648bce2fb84955d06f08d918e1ee21%7Cd79a81124fbe417aa112cd0fb490d85c%7C0%7C0%7C637568180918078371%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=t%2Bze6Xhhhaam8y%2B7aXUcpHNbGJTw%2ForOOv96aH%2Fcvx4%3D&reserved=0>.

To view the terms under which this email is distributed, please go to:-
http://leedsbeckett.ac.uk/disclaimer/email/

**Comment by hrz0001** [comment]
Hi Luke,

The command I was trying was :- ruby secgen.rb --scenario scenarios/examples/remotely_exploitable_user_vulnerability.xml run

Thanks,
Harsh Zaveri

**Comment by thompslu** [comment]
Ok so the command looks ok, when you installed the SecGen did you follow the exact steps. I would recommend you also looking at updating vagrant to a version newer .I know that’s not relevant but is recommended  other than what is on here,also did you follow the “bundle install for the gems” etc . As for resolving the scenario I will take a look this week around my schedule to see what’s happening, I will get back to you on this.

Kind Regards

Luke Thompson
________________________________

**Comment by thompslu** [comment]
So I’ve just reviewed the scenario, based on the scenario you’re trying to run it’s looking for a base that is named Debian_puppet32 or similar. This OS base is not included in the project anymore. You will need to change it to another OS base name for example debian _stretch_server or desktop (found in module bases) depending on what you want to try it on then go to the (scenario folder and edit the scenario.xml then re run ). Obviously with this been a project that can be developed upon it depends what you want to do. This is why the scenario was failing anyway hope that helps. Let me know how you get on.

Kind Regards

Luke Thompson
________________________________

**Comment by hrz0001** [comment]
Hi Luke,

I am trying to create a Scenario, where students can do CTF events while I build the main Scenario running on ESXI.
what would you suggest how to go with build with this Scenario? Also thanks for your reply I will try that out today.

Thanks,
Harsh Zaveri
