### ISSUE TITLE
Dependencies tag

### ISSUE THREAD

**Issue by Jjk422** [cliffe/SecGen#34]
Would a dependencies tag be best for the modules (in secgen_metadata.xml), so we say which modules are dependent on others, e.g. some services that require apt-get update to be done require an update module, or if we decide to create modules that create users and groups inputted from facter then we may need the tag. Just an idea.

Don't really know where to put this, that's why I'm putting this in issues.

**Comment by cliffe** [comment]
Yes. Just as we have "conflicts" in module secgen_metadata we should have "requires" to automatically add modules -- this should be straightforward to implement, and we could for example have service modules that install apache and vulnerability modules that misconfigure it (and require the service module to install it). Likewise for the apt-get update could be a module (which would ensure it only happens once rather than for every module that requires an update). The main issue will be if we end up with a complex set of conflicts and requires we may need a more intelligent dependency resolution system, rather than the brute force approach at the moment... In the meantime lets try to minimise the number of conflicts were we can, esp for modules required by others.

**Comment by cliffe** [comment]
Rather than code the requires feature now, please just create the modules and add the requires as a comment to the xml and create scenarios that simply include all the required modules.

**Comment by Jjk422** [comment]
OK, thanks for the quick feedback. And ye just doing modules at the moment.

**Comment by cliffe** [comment]
Great! :)

**Comment by Jjk422** [comment]
Can this issue be marked as resolved now?
