### ISSUE TITLE
Generated project/scenario.xml's: Escape backslashes in some xml attributes.

### ISSUE THREAD

**Issue by thomashaw** [cliffe/SecGen#37]
Some attributes in the generated project/SecGen2016xxxx/scenario.xml contain the backslash escape characters in the string.

Example:
![selection_015](https://cloud.githubusercontent.com/assets/3964474/16020294/3ad61138-31a5-11e6-8da1-c37af08c120c.png)

**Comment by cliffe** [comment]
Thanks, @thomashaw. This is actually a required feature because the scenario is comprised of module selection filters that are regexp expressions. The generated scenario file creates filters that will match the randomised module selection. The text therefore needs to have any special characters escaped. Note that the generated scenario could be simplified by leaving out most of the attributes (selection filters), since module_path alone is sufficient to match the specific module. However, I think the extra output is beneficial for readability.

**Comment by cliffe** [comment]
Also having all the attributes stored provides a record of the challenge solution, for marking etc
