### ISSUE TITLE
account values are appended in default input

### ISSUE THREAD

**Issue by meehien** [cliffe/SecGen#91]
A given `secgen_metadata.xml` of a module which contains:
```
<default_input into="accounts">
  <generator type="account">
      <input into="username">
        <value>jakesmith</value>
      </input>
   </generator>
 </default_input>
```
SecGen will produce an account with the name` jakesmithrandomvalue` instead of `jakesmith`.

**Comment by cliffe** [comment]
Thanks, @meehien. This looks like it might be related to a bug I am working on at the moment. I guess we should have opened an issue. Just to summarise `scenarios/examples/parameterised_examples/encoder_examples/parameterised_accounts.xml` will sometimes mess up use of default values. I am fairly sure that can be fixed by ensuring the default input objects are cloned when adding a module. Anyway, once that other bug is fixed we can see whether it was related.

**Comment by cliffe** [comment]
@meehien, it turns out it was an unrelated bug. I think this is now fixed in a pull request. We will update once merged.
